# Generated by Django 4.2.8 on 2023-12-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='location',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='status',
            field=models.BooleanField(),
        ),
    ]
