# Generated by Django 4.2.8 on 2023-12-09 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_place', '0002_alter_parkingspace_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
