# Generated by Django 4.2.8 on 2023-12-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_place', '0003_alter_parkingspace_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
