# Generated by Django 4.2.8 on 2023-12-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_place', '0004_alter_parkingspace_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
