# Generated by Django 4.2.8 on 2023-12-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_place', '0005_alter_parkingspace_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkingspace',
            unique_together={('date', 'time')},
        ),
    ]
