# Generated by Django 4.2.8 on 2023-12-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_place', '0006_alter_parkingspace_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkingspace',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='parkingspace',
            unique_together={('date', 'time', 'location')},
        ),
    ]
